### ISSUE TITLE
Search for parts of shell-commands containing colons

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/t3docs-search-indexer#31]
Shell commands often contain a colon without additional whitespace, for example "install:generatepackagestates" This leads to the effect that "install:generatepackagestates" will be found in the docs search but not "generatepackagestates" it would be great if both strings could be found even if the document only mentions "install:generatepackagestates" 

refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/177

**Comment by tmotyl** [comment]
@gr0 could you give me a hint how to handle it? I believe splitting on : would solve it? Probably related to https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/26#issuecomment-886228889 ?

**Comment by gr0** [comment]
Yes, you are right @tmotyl the splitting would help here - what I have in mind is using: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html. This should help with the described situation.

**Comment by tmotyl** [comment]
@gr0 right now we have config like
```
analysis:
  filter:
    typo3_stemmer:
      type: stemmer
      language: minimal_english
  analyzer:
    typo3_analyzer:
      filter:
      - lowercase
      - asciifolding
      - typo3_stemmer
      tokenizer: standard
 ```
 we're using standard tokenizer and acording to docs you've sent its discouraged "
Avoid using the word_delimiter filter with tokenizers that remove punctuation, such as the standard tokenizer"

Should we change the tokenizer also?
