### ISSUE TITLE
Code blocks are not indexed

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/t3docs-search-indexer#87]
I am searching for "ViewFactoryData" and getting no result. But it is available in a changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.3/Feature-104773-GenericViewFactory.html

**Comment by damienalexandre** [comment]
Is this the expected result?

![image](https://github.com/user-attachments/assets/9a943cf8-f01c-4e20-a2e9-f3382eb529b1)

https://docs.typo3.org/search/search?q=ViewFactoryInterface&filters%5Bdocument+type%5D%5BCore+changelog%5D=true

It looks like it's ok now?

**Comment by brotkrueml** [comment]
Yup, for this specific case, as the search term is now available in the text.

But code blocks are not indexed yet. I don't know, if they should be, maybe that is too much noise in the search results, but maybe with lower priority.
That's the decision for someone else to make. Just throwed it it, as this is an oversight or an intentional decision.

**Comment by linawolf** [comment]
This is actually a missing feature. @damienalexandre can you leave some information  on what is needed to achieve this?

**Comment by damienalexandre** [comment]
👍 

Right now, code example are removed from the documents and not indexed at all. See `\App\Service\ParseDocumentationHTMLService::stripCodeExamples` for the code.

In order to search in code, we need to keep those. BUT, mixing plain text and code can lead to polluted search results.

The analyzer used for text:

```yaml
  filter:
    typo3_stemmer:
      type: stemmer
      language: minimal_english
    typo3_filter:
       type: word_delimiter_graph
       preserve_original: true
  analyzer:
    typo3_analyzer:
      type: custom
      tokenizer: whitespace
      filter:
        - lowercase
        - asciifolding
        - typo3_filter
        - typo3_stemmer
```

Is not adapted / relevant for code, be it PHP, Yaml, JavaScript...

I think a good approach would be:

- extract the code parts in a new property
- build a dedicated "code" analyzer to properly sanitize and tokenize code from any language
- add this new field in the search
- add this new field in the highlights and display fragments mixed with the content fragments

To build the code analyzer, inspiration can be taken from GitLab own Elasticsearch implementation:

https://gitlab.com/gitlab-org/gitlab/-/blob/0fb01563c72fff468d58130cbcf50d6c6cb553df/ee/lib/elastic/latest/config.rb#L51-55

```
              code_analyzer: {
                type: 'custom',
                tokenizer: 'whitespace',
                filter: %w[word_delimiter_graph_filter flatten_graph lowercase asciifolding remove_duplicates]
              },
```

It's quite simple / efficient.
